CREATE TABLE tb_usuarios (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome VARCHAR(100),
                       email VARCHAR(100),
                       senha VARCHAR(50)

);