CREATE TABLE tb_enderecos (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              rua VARCHAR(255),
                              numero INTEGER,
                              complemento VARCHAR(255),
                              cidade VARCHAR(100),
                              estado VARCHAR(2),
                              cep VARCHAR(10),
                              usuario_id BIGINT,
                              FOREIGN KEY (usuario_id) REFERENCES tb_usuarios(id)
);