CREATE TABLE tb_telefones (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             numero VARCHAR(20),
                             ddd VARCHAR(3),
                             usuario_id BIGINT,
                             FOREIGN KEY (usuario_id) REFERENCES tb_usuarios(id)
);